In [1]:
import numpy as np

In [2]:
# squaring a number:
def square(number:int):
    return number**2
user_inp= int(input("Enter a number: "))
square(user_inp)

Enter a number:  18


324

In [3]:
def square(number:int):
    print(number**2)
user_inp= int(input("Enter a number: "))
square(user_inp)

Enter a number:  3


9


The main difference between print statement and `return` in a function is that `return` sends the value out to the function and can be stored after which it ends the function. print directly shows the result in the screen but cannot be used later, it is mostly used for debugging.


In [4]:
def area_of_sqr(side):
    return side*side
user_inp= float(input("Enter the side of the square: "))
area_of_sqr(user_inp)


Enter the side of the square:  3


9.0

In [5]:
def area_circle(radius):
    return 3.14*(radius**2)
user_inp= float(input("Enter the radius: "))
area_circle(user_inp)


Enter the radius:  45


6358.5

In [6]:
def area_sqr(side):
    return side*side

def area_circle(radius):
    return 3.14*(radius**2)

def area_rectangle(l,b):
    return l*b

user_choice= int(input("Enter your choice [1,2,3] for square, rectangle and circle respectively: "))
if user_choice == 1:
    user_inp= float(input("Enter the side of the square: "))
    result= area_of_sqr(user_inp)
    print(f"Area of the square is {result}")
elif user_choice==2:
    user_inp1= float(input("Enter the length: "))
    user_inp2= float(input("Enter the breadth: "))
    result= area_rectangle(user_inp1, user_inp2)
    print(f"Area of the rectangle is {result}")
elif user_choice==3:
    user_inp= float(input("Enter the radius: "))
    result= area_circle(user_inp)
    print(f"Area of the circle is {result}")
else:
    print("Invalid choice.")
    



Enter your choice [1,2,3] for square, rectangle and circle respectively:  1
Enter the side of the square:  4


Area of the square is 16.0


#### NumPy

In [7]:
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [8]:
a.shape

(5,)

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [12]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])
 
print(arr[0, 1])   # row 0, col 1
print(arr[1][2])   # row 1, col 2
print(arr[-1, -1]) # last row last column

20
60
60


In [13]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
 
print(a + 5) #scalar addition
print(a * 2) #scalar multiplication
print(a + b) #arr with arr

[15 25 35]
[20 40 60]
[11 22 33]


In [14]:
a = np.array([10.0, 20.0, 30.0])
b = np.array([1, 2, 3])
print(a + 5) #scalar addition
print(a * 2) #scalar multiplication
print(a + b) #arr with arr

[15. 25. 35.]
[20. 40. 60.]
[11. 22. 33.]


In [15]:
# Error thrown because the sizes of the arrays are not similar
a = np.array([10.0, 20.0, 30.0])
b = np.array([1, 2, 3, 4])
print(a + b) #arr with arr

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [16]:
a= np.arange(1,10).reshape(3,3)
b= np.arange(2,20,2).reshape(3,3)
c= a+b
c

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [17]:
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])
 
print("Total sum:", data.sum())
print("Column-wise mean:", data.mean(axis=0))
print("Column-wise max:", data.max(axis=0))
print("Row-wise max:", data.max(axis=1))
print("Overall min:", np.min(data))

Total sum: 450
Column-wise mean: [40. 50. 60.]
Column-wise max: [70 80 90]
Row-wise max: [30 60 90]
Overall min: 10


________________________________________________________________________________________________________________________

## Exercise:

https://drive.google.com/drive/folders/1ub-HsJc6aLAvgXfsv0bZSPJOM_FuUM-V?usp=drive_link

### Variables, Input & Operators
#### 1. Write a Python program that asks the user for their name, age, and city, then displays the information in a meaningful sentence.

In [18]:

from datetime import datetime
name= input("Enter your name: ")
birth_year= int(input("Enter your birth year: "))
city= input("Enter your city: ")

current_year= datetime.now().year
print(f"Hello! {name} from {city}. Your age is {current_year-birth_year}.")


Enter your name:  riri
Enter your birth year:  1800
Enter your city:  rome


Hello! riri from rome. Your age is 226.


#### 2. Write a program that asks the user for two numbers and displays their addition, subtraction, multiplication, and division.

In [19]:

def calculator(num1, num2, choice:int):
    if choice==1:
        return num1/num2
    elif choice==2:
        return num1 * num2
    elif choice==3:
        return num1 + num2
    else:
        return num1 - num2


# Dictionary for calculator
operations= {1: 'division', 2: 'multiplication', 3: 'addition', 4: 'subtraction'}

#user-input validation:
while True:
    user_choice= int(input(f"Enter your choice:\n1. Division \n2. Multiplication \n3. Addition \n4. Subtraction \n "))
    if user_choice> 4:
        print("Invalid Choice")
    else:
        num1= float(input("Enter your first number: "))
        num2= float(input("Enter your second number: "))
        result= calculator(num1, num2, user_choice)
        print(f"User chose {operations[user_choice]} for the numbers {num1} and {num2}. The result is {result}")
        user_inp= input("Do you want to continue [y/n]: ")
        if user_inp.lower()=='y':
            continue
        else: break
    



Enter your choice:
1. Division 
2. Multiplication 
3. Addition 
4. Subtraction 
  2
Enter your first number:  25
Enter your second number:  5


User chose multiplication for the numbers 25.0 and 5.0. The result is 125.0


Do you want to continue [y/n]:  n


#### 3. Write a program to calculate the area of a rectangle. Ask the user to enter the length and width.

In [20]:
def area_rectangle(l,b):
    return l*b
user_inp1= float(input("Enter the length: "))
user_inp2= float(input("Enter the breadth: "))
result= area_rectangle(user_inp1, user_inp2)
print(f"Area of rectangle with length {user_inp1} and breadth {user_inp2} is {result}")

Enter the length:  10
Enter the breadth:  25


Area of rectangle with length 10.0 and breadth 25.0 is 250.0


#### 4. Write a program that accepts a temperature in Celsius and converts it to Fahrenheit.

In [21]:
def celsius_to_fahrenheit(temp_cel):
    return ((temp_cel* 1.8) + 32)

user_inp= float(input("Enter the temperature in Celsius: "))
result= celsius_to_fahrenheit(user_inp)
print(f"The temperature is {result}F for {user_inp}C")

Enter the temperature in Celsius:  20.0


The temperature is 68.0F for 20.0C


### if / elif / else


#### 5. Write a program that asks the user for a number and determines whether it is positive, negative, or zero.

In [22]:
user_inp= int(input("Enter any number: "))
if user_inp > 0:
    print("User entered a positive number.")
elif user_inp< 0:
    print("User entered a negative number.")
else:
    print("User entered zero.")

Enter any number:  -7


User entered a negative number.


#### 6. Write a program that asks the user for a number and determines whether it is even or odd.

In [23]:
user_inp= int(input("Enter any number: "))
if user_inp%2 == 0:
    print(f"User entered even number: {user_inp}")
else:
    print(f"User entered odd number: {user_inp}")
    

Enter any number:  34


User entered even number: 34


#### 7. Write a program that asks for a person's age and determines whether they are a child, teenager, or adult.

In [24]:
from datetime import datetime

birth_year= int(input("Enter your birth year: "))
current_year= datetime.now().year

age= current_year - birth_year

#Conditional logic: 
if age > 19:
    print(f"Welcome to Adulthood, you current age is {age}!!")
elif age<= 19 and age >= 13:
    print(f"You are a teenager, your current age is {age}!!")
else: print(f"You are still a child, your current age is {age}!!")


Enter your birth year:  1800


Welcome to Adulthood, you current age is 226!!


#### 8. Write a program that accepts marks from 0 to 100 and displays the appropriate grade:

90–100 → A 

80–89 → B 

70–79 → C 

60–69 → D 

Below 60 → F 

In [25]:
score= float(input("Enter your score: "))

#added boundary conditins for negative value or value greater than 100

if score >= 90 and score <= 100:
    print("Your grade is A")
elif score>=80 and score < 90:
    print("Your grade is B")
elif score>=70 and score <80:
    print("Your grade is C")
elif score>=60 and score < 70:
    print("Your grade is D")
elif score>= 0 and score < 60:
    print("Your grade is F")
else:
    print("Not a valid score!!")
    

Enter your score:  170


Not a valid score!!


#### 9. Write a program that asks for three numbers and finds the largest number.

In [26]:
num1, num2, num3= map(int, input("Enter three numbers seprated by spaces: ").split()) # map each element as int
lis= [num1, num2, num3]
max(lis)

Enter three numbers seprated by spaces:  25 180 35


180

#### 10. Write a simple calculator. Ask the user for two numbers and an operator (+, -, *, /) and perform the selected calculation.

In [27]:

def calculator(num1, num2, choice:int):
    if choice==1:
        return num1/num2
    elif choice==2:
        return num1 * num2
    elif choice==3:
        return num1 + num2
    else:
        return num1 - num2


# Dictionary for calculator
operations= {1: 'division', 2: 'multiplication', 3: 'addition', 4: 'subtraction'}

#user-input validation:
while True:
    user_choice= int(input(f"Enter your choice:\n1. Division \n2. Multiplication \n3. Addition \n4. Subtraction \n "))
    if user_choice> 4:
        print("Invalid Choice")
    else:
        num1= float(input("Enter your first number: "))
        num2= float(input("Enter your second number: "))
        result= calculator(num1, num2, user_choice)
        print(f"User chose {operations[user_choice]} for the numbers {num1} and {num2}. The result is {result}")
        user_inp= input("Do you want to continue [y/n]: ")
        if user_inp.lower()=='y':
            continue
        else: break

Enter your choice:
1. Division 
2. Multiplication 
3. Addition 
4. Subtraction 
  1
Enter your first number:  15
Enter your second number:  5


User chose division for the numbers 15.0 and 5.0. The result is 3.0


Do you want to continue [y/n]:  y
Enter your choice:
1. Division 
2. Multiplication 
3. Addition 
4. Subtraction 
  3
Enter your first number:  15
Enter your second number:  5


User chose addition for the numbers 15.0 and 5.0. The result is 20.0


Do you want to continue [y/n]:  n


### for Loops

#### 11. Write a program using a for loop to print numbers from 1 to 20.

In [30]:
reverse_lis= []
for i in range(1,21)[::-1]: #print in reverse order
    reverse_lis.append(i)
print(reverse_lis)

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


#### 12. Write a program to print all even numbers between 1 and 50.

In [31]:
even_lis= []
for i in range(2, 51, 2):
    even_lis.append(i)
print(even_lis)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


#### 13. Write a program to print all numbers between 1 and 100 that are divisible by both 3 and 5.

In [33]:
output= []
for i in range(1, 101):
    if i%3 == 0 and i%5== 0:
        output.append(i)
print(f"Number that are divisible by both 3 and 5 are {output}")
        

Number that are divisible by both 3 and 5 are [15, 30, 45, 60, 75, 90]


#### 14. Write a program to display the multiplication table of a number entered by the user.

In [35]:
def multiplication_table(number):
    for i in range(1,11):
        print(f"{number} x {i} = {number * i}")

while True:
    user_inp= int(input("Enter a number to see their multiplication table: "))
    multiplication_table(user_inp)
    user_continue= input("Do you want to try for another number? [y/n]")
    if user_continue.lower()== 'y':
        continue
    else: break

Enter a number to see their multiplication table:  2


2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20


Do you want to try for another number? [y/n] y
Enter a number to see their multiplication table:  5


5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


Do you want to try for another number? [y/n] n


#### 15. Write a program to calculate the sum of all numbers from 1 to 100 using a for loop.

In [39]:
sum_lis= []
for i in range(1, 101):
    sum_lis.append(i)
#print(sum_lis)
print(f"Sum of all the elements from 1 to 100 would be: {sum(sum_lis)}")

Sum of all the elements from 1 to 100 would be: 5050


#### 16. Write a program to count how many even numbers exist between 1 and 100.

In [41]:
even_lis=[]

for i in range(1, 101):
    if i%2==0:
        even_lis.append(i)

print(even_lis)
print(f"Number of all even elements from 1 to 100 would be: {len(even_lis)}")


[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]
Number of all even elements from 1 to 100 would be: 50


### Lists + Loops



#### 17. Given the following list:
numbers = [12, 45, 7, 89, 23, 56, 34, 91, 10]

Use a for loop to print:

All even numbers 

All odd numbers 

All numbers greater than 50 

In [43]:
numbers = [12, 45, 7, 89, 23, 56, 34, 91, 10]
even_num_lis= [num for num in numbers if num%2==0]
odd_num_lis= [num for num in numbers if num%2!=0]
num_lis= [num for num in numbers if num > 50]

print(even_num_lis)
print(odd_num_lis)
print(num_lis)

[12, 56, 34, 10]
[45, 7, 89, 23, 91]
[89, 56, 91]


#### 18. Given a list of numbers, calculate the total without using the built-in sum() function.

In [44]:
numbers = [12, 45, 7, 89, 23, 56, 34, 91, 10]
sum_of_numbers= 0
for number in numbers:
    sum_of_numbers+= number

print(sum_of_numbers)
    

367


#### 19. Given a list of numbers, find the largest number without using the built-in max() function.

In [46]:
numbers = [12, 45, 7, 89, 23, 56, 34, 91, 10]
max_num= 0
for number in numbers:
    if number > max_num:
        max_num= number
print(seen_num)
    

91


#### 20. Given a list of student marks, use a loop to count how many students passed and how many failed. A mark of 40 or above is considered a pass.

In [50]:
numbers = [12, 45, 7, 89, 23, 56, 34, 91, 10]
pass_count= 0
fail_count= 0

for i in numbers:
    if i >= 40:
        pass_count+= 1
    else: fail_count+= 1
print(f"Number of students passed is {pass_count}")
print(f"Number of students failed is {fail_count}")

Number of students passed is 4
Number of students failed is 5


### Functions

#### 21. Write a function greet_user(name) that accepts a person's name and returns a greeting message.

In [52]:
def greet_user(name:str):
    print(f"Hello {name.title()}! Glad to meet you.")

greet_user("riri")

Hello Riri! Glad to meet you.


#### 22. Write a function check_even_odd(number) that accepts a number and returns "Even" or "Odd".

In [53]:
def check_even_odd(number: int):
    if number%2== 0:
        print(f"The number {number} is Even.")
    else:
        print(f"The number {number} is Odd.")

check_even_odd(15)

The number 15 is Odd.


#### 23. Write a function calculate_sum(n) that uses a loop to calculate and return the sum of numbers from 1 to n.

In [56]:
def calculate_sum(list_of_numbers: list):
    sum_of_n= 0
    for element in list_of_numbers:
        sum_of_n+= element
    return sum_of_n

lis= [5, 10, 15, 20, 25, 20, 35, 40]
result= calculate_sum(lis)
print(f"Sum of {lis} is: {result}")

Sum of [5, 10, 15, 20, 25, 20, 35, 40] is: 170


#### 24. Write a function count_greater(numbers, value) that accepts a list of numbers and a value, and returns how many numbers in the list are greater than that value.

In [63]:
import random
def count_greater(numbers: list, value: int):
    count= 0
    max_lis= []
    for num in numbers:
        if num > value:
            count+=1
            max_lis.append(num)
    return count, max_lis
lis_of_items= [i for i in range(1,60)]
value= random.randrange(20, 80)
result, max_lis= count_greater(lis_of_items, value)
print(f"List of items: {lis_of_items}")
print(f"Random value generated: {value}")
if result== 0:
    print(f"No numbers greater than {value} is found.")
else:
    print(f"{result} numbers are greater than {value}: {max_lis}")
    

List of items: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]
Random value generated: 57
2 numbers are greater than 57: [58, 59]


### ⭐ Combined Challenge

### 25. Write a function called analyze_numbers(numbers) that accepts a list of numbers and calculates:

- Total number of values 
- Sum of the values 
- Average 
- Largest value 
- Smallest value 
- Number of even values 
- Number of odd values

In [91]:
import numpy as np

arr= np.arange(1,28)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [92]:
len(arr) #Total number of values



27

In [93]:
np.sum(arr) #Sum of values

378

In [94]:
np.mean(arr) #Average

14.0

In [95]:
np.max(arr) # Larget value

27

In [96]:
np.min(arr) # Smallest Value

1

In [97]:
np.sum(arr%2 == 0) # number of even values

13

In [98]:
np.sum(arr%2 != 0) # number of odd values

14

____________________________________________________________________________________________________________________